routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('storage-link', function (){
    \Illuminate\Support\Facades\Artisan::call('storage:link');
});

Auth::routes();

Route::post('quotation', [\App\Http\Controllers\EmailsController::class, 'quotation'])->name('quotation');


Route::group(['middleware' => ['lang']], function () {
    Route::get('lang/{lang}', function ($lang) {
        session(['lang' => $lang]);
        return \Redirect::back();
    })->where([
        'lang' => 'en|es'
    ]);
    Route::get('/', [\App\Http\Controllers\MainController::class, 'index'])->name('index');
    Route::get('/noticias', [\App\Http\Controllers\MainController::class, 'index'])->name('news');
    Route::get('/testimoniales', [\App\Http\Controllers\MainController::class, 'index'])->name('testimonials');
    Route::get('/aviso-de-privacidad', [\App\Http\Controllers\MainController::class, 'noticePrivacy'])->name('noticeOfPrivacy');
    Route::get('/quienes-somos', [\App\Http\Controllers\MainController::class, 'about'])->name('about');
    Route::get('/servicios/{item}', [\App\Http\Controllers\MainController::class, 'services'])->name('services');
    Route::get('/eventos', [\App\Http\Controllers\MainController::class, 'events'])->name('events');
    Route::get('/eventos/{slug}', [\App\Http\Controllers\FairController::class, 'show'])->name('event');
    Route::post('/events/component', [\App\Http\Controllers\MainController::class, 'eventsChange']);
    Route::get('/extensiones', [\App\Http\Controllers\MainController::class, 'extensions'])->name('extensions');
    Route::get('/extensiones/{slug}', [\App\Http\Controllers\ExtensionController::class, 'show'])->name('extension');
    Route::post('/extensions/component', [\App\Http\Controllers\MainController::class, 'extensionsChange']);
    Route::get('/mexico', [\App\Http\Controllers\MainController::class, 'mexico'])->name('mexico');
    Route::get('/mexico/{slug}', [\App\Http\Controllers\MexicoController::class, 'show'])->name('mex');
    Route::post('/mexico/component', [\App\Http\Controllers\MainController::class, 'mexicoChange']);
    Route::get('/viajes-especiales', [\App\Http\Controllers\MainController::class, 'specialTrips'])->name('specialTrips');
    Route::get('/viajes-especiales/{slug}', [\App\Http\Controllers\SpecialTripsContoller::class, 'show'])->name('specialTrip');
    Route::post('/viajes_especiales/component', [\App\Http\Controllers\MainController::class, 'specialTripsChange']);
    Route::get('/testimoniales', [\App\Http\Controllers\MainController::class, 'testimonials'])->name('testimonials');
    Route::get('/noticias', [\App\Http\Controllers\MainController::class, 'news'])->name('news');
    Route::get('/noticias/{slug}', [\App\Http\Controllers\MainController::class, 'newsShow'])->name('newsShow');
    Route::get('/blog', [\App\Http\Controllers\MainController::class, 'blogs'])->name('blogs');
    Route::get('/blog/{slug}', [\App\Http\Controllers\MainController::class, 'blog'])->name('blog');
    Route::get('/ofertas', [\App\Http\Controllers\MainController::class, 'offers'])->name('offers');
    Route::post('/offers/component', [\App\Http\Controllers\MainController::class, 'offersChange']);
    Route::get('/ofertas/{slug}', [\App\Http\Controllers\OfferController::class, 'show'])->name('offer');
    Route::get('/contacto', [\App\Http\Controllers\MainController::class, 'contact'])->name('contact');
});


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'lang']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('/leagues', \App\Http\Controllers\LeagueController::class)->except(['show']);
    Route::post('/leagues/active/{id}', [\App\Http\Controllers\LeagueController::class, 'active'])->name('leagues.active');
    Route::resource('/fairs', \App\Http\Controllers\FairController::class)->except(['show']);
    Route::post('/fairs/active/{id}', [\App\Http\Controllers\FairController::class, 'active'])->name('fairs.active');
    Route::post('/fairs/star/{id}', [\App\Http\Controllers\FairController::class, 'star'])->name('fairs.star');
    Route::resource('/extensions', \App\Http\Controllers\ExtensionController::class)->except(['show']);
    Route::post('/extensions/active/{id}', [\App\Http\Controllers\ExtensionController::class, 'active'])->name('extensions.active');
    Route::resource('/mexico', \App\Http\Controllers\MexicoController::class)->except(['show']);
    Route::post('/mexico/active/{id}', [\App\Http\Controllers\MexicoController::class, 'active'])->name('mexico.active');
    Route::resource('/trips', \App\Http\Controllers\SpecialTripsContoller::class)->except(['show']);
    Route::post('/trips/active/{id}', [\App\Http\Controllers\SpecialTripsContoller::class, 'active'])->name('trips.active');
    Route::resource('/news', \App\Http\Controllers\NewsController::class)->except(['show']);
    Route::post('/news/active/{id}', [\App\Http\Controllers\NewsController::class, 'active'])->name('news.active');
    Route::resource('/blogs', \App\Http\Controllers\BlogController::class)->except(['show']);
    Route::post('/blogs/active/{id}', [\App\Http\Controllers\BlogController::class, 'active'])->name('blogs.active');
    Route::resource('/offers', \App\Http\Controllers\OfferController::class)->except(['show']);
    Route::post('/offers/active/{id}', [\App\Http\Controllers\OfferController::class, 'active'])->name('offers.active');
    Route::resource('/images', \App\Http\Controllers\ImageController::class)->except(['show', 'index', 'update', 'edit']);
    Route::get('/images/{id}', [\App\Http\Controllers\ImageController::class, 'destroy'])->name('images.destroy');
    Route::resource('/promotions', \App\Http\Controllers\PromotionController::class)->except(['show']);
    Route::post('/promotions/active/{id}', [\App\Http\Controllers\PromotionController::class, 'active'])->name('promotions.active');
    Route::resource('/users', \App\Http\Controllers\UserController::class)->except(['show']);
    Route::post('/users/active/{id}', [\App\Http\Controllers\UserController::class, 'active'])->name('users.active');
    Route::resource('/destination/management', \App\Http\Controllers\DestinationManagementController::class)->except(['show']);
    Route::post('/destination/management/active/{id}', [\App\Http\Controllers\DestinationManagementController::class, 'active'])->name('management.active');
});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Translatable\HasTranslations;

class News extends Model
{
    use HasFactory, SoftDeletes, HasTranslations;

    protected $table = "news";
    public $translatable = ['slug', 'title', 'intro', 'content'];

    public $fillable = ['title', 'intro', 'content', 'image', 'active', 'date'];
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Models\News;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str as Str;

class NewsController extends Controller
{

    protected $title;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->title = 'Noticias';
        View::share('title', $this->title);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $newsAll = News::where('type', 'news')->orderBy('date', 'asc')->get();
        return view('administrador.news.list', compact('newsAll'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrador.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $image = $request->file('image');
        $data = $request->validate([
            'title' => 'required',
            'intro' => 'required',
            'content' => 'required'
        ],[
            'title.required' => 'El campo titulo es obligatorio',
            'intro.required' => 'El campo introducción es obligatorio',
            'content.required' => 'El campo contenido es obligatorio',
        ]);
        $news = new News();
        $news->title = $data['title'];
        $news->slug = Str::slug($data['title']);
        $news->intro = $data['intro'];
        $news->content = $data['content'];
        $news->date = date_create('now');
        $news->type = 'news';
        if($image) {
            $nameImage = time() . "_" . $image->getClientOriginalName();
            Storage::disk('public')->put('/images/news/' . $nameImage, \File::get($image));
            $news->image = '/storage/images/news/'.$nameImage;
        }
        $news->save();

        return redirect('admin/news')->with('success', 'Se creo con exito la noticia');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function show(News $news)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {
        return view('administrador.news.edit', compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        $image = $request->file('image');
        $data = $request->validate([
            'title' => 'required',
            'intro' => 'required',
            'content' => 'required'
        ],[
            'title.required' => 'El campo titulo es obligatorio',
            'intro.required' => 'El campo introducción es obligatorio',
            'content.required' => 'El campo contenido es obligatorio',
        ]);
        $news->title = $data['title'];
        $news->intro = $data['intro'];
        $news->content = $data['content'];
        $news->date = date_create('now');
        if($image) {
            $nameImage = time() . "_" . $image->getClientOriginalName();
            Storage::disk('public')->put('/images/news/' . $nameImage, \File::get($image));
            $news->image = '/storage/images/news/'.$nameImage;
        }
        $news->save();
        return redirect('admin/news')->with('success', 'Se actualizo con exito la noticia');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        $news->delete();
        return redirect('admin/news')->with('success', 'Se elimino con exito la noticia');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function active($id)
    {
        $news = News::findOrFail($id);
        if($news->active){
            $news->active = false;
            $result = 'desactivo';
        } else {
            $news->active = true;
            $result = 'activo';
        }
        $news->save();
        return redirect('admin/news')->with('success', 'La noticia se '. $result.' correctamente');
    }
}

resources/views/administrador/news/create.blade.php
@extends('administrador.layouts.app-admin')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1">
                <div class="row">
                    <div class="col-12 d-flex justify-content-between">
                        @if($title == 'Noticias')
                            <h1>Crear Nueva Noticia</h1>
                            <div class="col-2">
                                <a href="{{route('news.index')}}" class="btn btn-primary">
                                    <i class="fa fa-list"></i>
                                    Lista
                                </a>
                            </div>
                        @elseif($title == 'Blog')
                            <h1>Crear Nuevo Blog</h1>
                            <div class="col-2">
                                <a href="{{route('blogs.index')}}" class="btn btn-primary">
                                    <i class="fa fa-list"></i>
                                    Lista
                                </a>
                            </div>
                        @endif

                    </div>
                </div>
                @if($title == 'Noticias')
                    <form class="validate-form mb-5" method="POST" action="{{route('news.store')}}" enctype="multipart/form-data">
                @elseif($title == 'Blog')
                    <form class="validate-form mb-5" method="POST" action="{{route('blogs.store')}}" enctype="multipart/form-data">
                @endif
                    @csrf
                    <div class="row mt-5">
                        <div class="col-12">
                            <label for="">
                                @if(App::islocale('es'))
                                    <i class="fa fa-flag text-success"></i>
                                @endif
                                @if(App::islocale('en'))
                                    <i class="fa fa-flag text-info"></i>
                                @endif
                                Titulo
                            </label>
                                <input type="text" class="form-control mt-3 @error('title') is-invalid @enderror" placeholder="Titulo" name="title" value="{{old('title')}}">
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-12">
                            <label for="">
                                @if(App::islocale('es'))
                                    <i class="fa fa-flag text-success"></i>
                                @endif
                                @if(App::islocale('en'))
                                    <i class="fa fa-flag text-info"></i>
                                @endif
                                Introducción
                            </label>
                            <textarea class="ckeditor mt-3 @error('intro') is-invalid @enderror" placeholder="Introducción"
                                      name="intro" value="{{old('intro')}}">{{old('intro')}}</textarea>
                            @error('intro')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-12">
                            <label for="">
                                @if(App::islocale('es'))
                                    <i class="fa fa-flag text-success"></i>
                                @endif
                                @if(App::islocale('en'))
                                    <i class="fa fa-flag text-info"></i>
                                @endif
                                Contenido
                            </label>
                            <textarea class="ckeditor mt-3 @error('content') is-invalid @enderror" placeholder="Contenido"
                                      name="content" value="{{old('content')}}">{{old('content')}}</textarea>
                            @error('content')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-4">
                            <label class="text-center">Imagen</label>
                            <br>
                            <img src="{{asset('images/missing.png')}}" class="img-fluid" alt="Sin imagen" id="image">
                        </div>
                        <div class="col-8">
                            <br><br>
                            <div class="alert alert-primary" role="alert">
                                <i class="fa fa-file-image"></i>
                                Imagen (Formato png, jpg o jpeg 230 x 360 resolución 72 dpi, max 900Kb )<br>
                            </div>

                            <div class="upload-btn-wrapper" id="btn">
                                <button class="btn btn-primary">Selecciona un archivo</button>
                                <input type="file" name="image" accept="image/*" onchange="loadFile(event)">
                            </div>
                            <div id="delete">
                                <a class="btn btn-danger" onclick="deletePoster()">Eliminar Imagen</a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <input type="checkbox" class="checkbox" name="active" id="active" checked>
                            <label for="active">Activo</label>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-3 offset-9">
                            <button type="submit" class="btn btn-block btn-primary">
                                <i class="fa fa-save"></i>
                                Guardar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        document.getElementById('delete').style.display = 'none';
        function deletePoster(){
            document.getElementById('delete').style.display = 'none';
            document.getElementById('btn').style.display = 'block';
            var image = document.getElementById('image');
            image.src = '/images/missing.png';
            image.value = "";
        }
        var loadFile = function(event) {
            var reader = new FileReader();
            reader.onload = function(){
                var image = document.getElementById('image');
                image.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
            document.getElementById('btn').style.display = 'none';
            document.getElementById('delete').style.display = 'block';
        };
    </script>
@endsection

resources/views/administrador/news/edit.blade.php
@extends('administrador.layouts.app-admin')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1">
                <div class="row">
                    <div class="col-12 d-flex justify-content-between">
                        @if($title == 'Noticias')
                            <h1>Editar Noticia</h1>
                            <div class="col-2">
                                <a href="{{route('news.index')}}" class="btn btn-primary">
                                    <i class="fa fa-list"></i>
                                    Lista
                                </a>
                            </div>
                        @elseif($title == 'Blog')
                            <h1>Editar Blog</h1>
                            <div class="col-2">
                                <a href="{{route('blogs.index')}}" class="btn btn-primary">
                                    <i class="fa fa-list"></i>
                                    Lista
                                </a>
                            </div>
                        @endif
                    </div>
                </div>
                @if($title == 'Noticias')
                    <form class="validate-form mb-5" method="POST" action="{{route('news.update', ['news' => $news->id])}}" enctype="multipart/form-data">
                @elseif($title == 'Blog')
                    <form class="validate-form mb-5" method="POST" action="{{route('blogs.update', ['blog' => $news->id])}}" enctype="multipart/form-data">
                @endif
                    @csrf
                    @method('PUT')
                    <div class="row mt-5">
                        <div class="col-12">
                            <label for="">
                                @if(App::islocale('es'))
                                    <i class="fa fa-flag text-success"></i>
                                @endif
                                @if(App::islocale('en'))
                                    <i class="fa fa-flag text-info"></i>
                                @endif
                                Titulo
                            </label>
                            <input type="text" class="form-control mt-3 @error('title') is-invalid @enderror" placeholder="Titulo" name="title" value="{{old('name', $news->title)}}">
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-12">
                            <label for="">
                                @if(App::islocale('es'))
                                    <i class="fa fa-flag text-success"></i>
                                @endif
                                @if(App::islocale('en'))
                                    <i class="fa fa-flag text-info"></i>
                                @endif
                                Introducción
                            </label>
                            <textarea class="ckeditor mt-3 @error('intro') is-invalid @enderror" placeholder="Introducción"
                                      name="intro" value="{{old('intro', $news->intro)}}">{{old('content', $news->intro)}}</textarea>
                            @error('intro')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-12">
                            <label for="">
                                @if(App::islocale('es'))
                                    <i class="fa fa-flag text-success"></i>
                                @endif
                                @if(App::islocale('en'))
                                    <i class="fa fa-flag text-info"></i>
                                @endif
                                Contenido
                            </label>
                            <textarea class="ckeditor mt-3 @error('content') is-invalid @enderror" placeholder="Contenido"
                                      name="content" value="{{old('content', $news->content)}}">{{old('content', $news->content)}}</textarea>
                            @error('content')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-4">
                            <label class="text-center">Poster</label>
                            <br>
                            @if($news->image)
                                <img src="{{asset($news->image)}}" class="img-fluid image" alt="{{$news->image}}" id="image">
                            @else
                                <img src="{{asset('images/missing.png')}}" class="img-fluid image" alt="Sin imagen" id="image">
                            @endif
                        </div>
                        <div class="col-8">
                            <br><br>
                            <div class="alert alert-primary" role="alert">
                                <i class="fa fa-file-image"></i>
                                Poster (Formato png, jpg o jpeg 230 x 360 resolución 72 dpi, max 900Kb )<br>
                            </div>

                            <div class="upload-btn-wrapper" id="btn">
                                <button class="btn btn-primary">Selecciona un archivo</button>
                                <input type="file" name="image" accept="image/*" onchange="loadFile(event)">
                            </div>
                            <div id="delete">
                                <a class="btn btn-danger" onclick="deletePoster()">Eliminar Imagen</a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <input type="checkbox" class="checkbox" name="active" id="active" checked>
                            <label for="active">Activo</label>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-3 offset-9">
                            <button type="submit" class="btn btn-block btn-primary">
                                <i class="fa fa-edit"></i>
                                Actualizar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        document.getElementById('delete').style.display = 'none';
        function deletePoster(){
            document.getElementById('delete').style.display = 'none';
            document.getElementById('btn').style.display = 'block';
            var image = document.getElementById('image');
            image.src = '/images/missing.png';
            image.value = "";
        }
        var loadFile = function(event) {
            var reader = new FileReader();
            reader.onload = function(){
                var image = document.getElementById('image');
                image.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
            document.getElementById('btn').style.display = 'none';
            document.getElementById('delete').style.display = 'block';
        };
    </script>
@endsection