routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('storage-link', function (){
    \Illuminate\Support\Facades\Artisan::call('storage:link');
});

Auth::routes();

Route::post('quotation', [\App\Http\Controllers\EmailsController::class, 'quotation'])->name('quotation');


Route::group(['middleware' => ['lang']], function () {
    Route::get('lang/{lang}', function ($lang) {
        session(['lang' => $lang]);
        return \Redirect::back();
    })->where([
        'lang' => 'en|es'
    ]);
    Route::get('/', [\App\Http\Controllers\MainController::class, 'index'])->name('index');
    Route::get('/noticias', [\App\Http\Controllers\MainController::class, 'index'])->name('news');
    Route::get('/testimoniales', [\App\Http\Controllers\MainController::class, 'index'])->name('testimonials');
    Route::get('/aviso-de-privacidad', [\App\Http\Controllers\MainController::class, 'noticePrivacy'])->name('noticeOfPrivacy');
    Route::get('/quienes-somos', [\App\Http\Controllers\MainController::class, 'about'])->name('about');
    Route::get('/servicios/{item}', [\App\Http\Controllers\MainController::class, 'services'])->name('services');
    Route::get('/eventos', [\App\Http\Controllers\MainController::class, 'events'])->name('events');
    Route::get('/eventos/{slug}', [\App\Http\Controllers\FairController::class, 'show'])->name('event');
    Route::post('/events/component', [\App\Http\Controllers\MainController::class, 'eventsChange']);
    Route::get('/extensiones', [\App\Http\Controllers\MainController::class, 'extensions'])->name('extensions');
    Route::get('/extensiones/{slug}', [\App\Http\Controllers\ExtensionController::class, 'show'])->name('extension');
    Route::post('/extensions/component', [\App\Http\Controllers\MainController::class, 'extensionsChange']);
    Route::get('/mexico', [\App\Http\Controllers\MainController::class, 'mexico'])->name('mexico');
    Route::get('/mexico/{slug}', [\App\Http\Controllers\MexicoController::class, 'show'])->name('mex');
    Route::post('/mexico/component', [\App\Http\Controllers\MainController::class, 'mexicoChange']);
    Route::get('/viajes-especiales', [\App\Http\Controllers\MainController::class, 'specialTrips'])->name('specialTrips');
    Route::get('/viajes-especiales/{slug}', [\App\Http\Controllers\SpecialTripsContoller::class, 'show'])->name('specialTrip');
    Route::post('/viajes_especiales/component', [\App\Http\Controllers\MainController::class, 'specialTripsChange']);
    Route::get('/testimoniales', [\App\Http\Controllers\MainController::class, 'testimonials'])->name('testimonials');
    Route::get('/noticias', [\App\Http\Controllers\MainController::class, 'news'])->name('news');
    Route::get('/noticias/{slug}', [\App\Http\Controllers\MainController::class, 'newsShow'])->name('newsShow');
    Route::get('/blog', [\App\Http\Controllers\MainController::class, 'blogs'])->name('blogs');
    Route::get('/blog/{slug}', [\App\Http\Controllers\MainController::class, 'blog'])->name('blog');
    Route::get('/ofertas', [\App\Http\Controllers\MainController::class, 'offers'])->name('offers');
    Route::post('/offers/component', [\App\Http\Controllers\MainController::class, 'offersChange']);
    Route::get('/ofertas/{slug}', [\App\Http\Controllers\OfferController::class, 'show'])->name('offer');
    Route::get('/contacto', [\App\Http\Controllers\MainController::class, 'contact'])->name('contact');
});


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'lang']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('/leagues', \App\Http\Controllers\LeagueController::class)->except(['show']);
    Route::post('/leagues/active/{id}', [\App\Http\Controllers\LeagueController::class, 'active'])->name('leagues.active');
    Route::resource('/fairs', \App\Http\Controllers\FairController::class)->except(['show']);
    Route::post('/fairs/active/{id}', [\App\Http\Controllers\FairController::class, 'active'])->name('fairs.active');
    Route::post('/fairs/star/{id}', [\App\Http\Controllers\FairController::class, 'star'])->name('fairs.star');
    Route::resource('/extensions', \App\Http\Controllers\ExtensionController::class)->except(['show']);
    Route::post('/extensions/active/{id}', [\App\Http\Controllers\ExtensionController::class, 'active'])->name('extensions.active');
    Route::resource('/mexico', \App\Http\Controllers\MexicoController::class)->except(['show']);
    Route::post('/mexico/active/{id}', [\App\Http\Controllers\MexicoController::class, 'active'])->name('mexico.active');
    Route::resource('/trips', \App\Http\Controllers\SpecialTripsContoller::class)->except(['show']);
    Route::post('/trips/active/{id}', [\App\Http\Controllers\SpecialTripsContoller::class, 'active'])->name('trips.active');
    Route::resource('/news', \App\Http\Controllers\NewsController::class)->except(['show']);
    Route::post('/news/active/{id}', [\App\Http\Controllers\NewsController::class, 'active'])->name('news.active');
    Route::resource('/blogs', \App\Http\Controllers\BlogController::class)->except(['show']);
    Route::post('/blogs/active/{id}', [\App\Http\Controllers\BlogController::class, 'active'])->name('blogs.active');
    Route::resource('/offers', \App\Http\Controllers\OfferController::class)->except(['show']);
    Route::post('/offers/active/{id}', [\App\Http\Controllers\OfferController::class, 'active'])->name('offers.active');
    Route::resource('/images', \App\Http\Controllers\ImageController::class)->except(['show', 'index', 'update', 'edit']);
    Route::get('/images/{id}', [\App\Http\Controllers\ImageController::class, 'destroy'])->name('images.destroy');
    Route::resource('/promotions', \App\Http\Controllers\PromotionController::class)->except(['show']);
    Route::post('/promotions/active/{id}', [\App\Http\Controllers\PromotionController::class, 'active'])->name('promotions.active');
    Route::resource('/users', \App\Http\Controllers\UserController::class)->except(['show']);
    Route::post('/users/active/{id}', [\App\Http\Controllers\UserController::class, 'active'])->name('users.active');
    Route::resource('/destination/management', \App\Http\Controllers\DestinationManagementController::class)->except(['show']);
    Route::post('/destination/management/active/{id}', [\App\Http\Controllers\DestinationManagementController::class, 'active'])->name('management.active');
});

app/Http/Controllers/ExtensionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Destination;
use App\Models\Extension;
use App\Models\Image;
use App\Models\League;
use App\Models\Region;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str as Str;

class ExtensionController extends Controller
{
    protected $title;
    protected $type;
    protected $url;
    protected $single;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->title = "Extensiones";
        $this->type = "extensions";
        $this->single = "Extensión";
        $this->url = 'extensiones';

        $destinations = [];
        $destinationsAll = Destination::get();
        $destinationsMexico = Region::where('type', 2)->get();
        $regions = Region::where('type', 1)->get();
        $categories = Category::get();
        $leagues = League::get();

        View::share('title', $this->title);
        View::share('type', $this->type);
        View::share('url', $this->url);
        View::share('single', $this->single);
        View::share('destinations', $destinations);
        View::share('destinationsAll', $destinationsAll);
        View::share('destinationsMexico', $destinationsMexico);
        View::share('regions', $regions);
        View::share('categories', $categories);
        View::share('leagues', $leagues);
    }


        /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $extensions = Extension::where('type' , 'extension')->get();
        return view('administrador.extensions.list', compact('extensions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrador.extensions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        config(['app.locale' => 'es']);
        $extension = new Extension($request->all());
        $extension->slug = Str::slug($extension->name);
        $extension->type = 'extension';
        $extension->region_id = $request['region'];
        $itinerary_file = $request->file('itinerary_file');
        if($itinerary_file) {
            $nameItinerary_file = "pdf_".time().".".$itinerary_file->guessExtension();
            Storage::disk('public')->put('/files/extensions/' . $nameItinerary_file, \File::get($itinerary_file));
            $extension->itinerary_file = '/storage/files/extensions/'.$nameItinerary_file;
        }
        $extension->destination_id = $request['destination_id'];
        $extension->category_id = $request['category'];
        $extension->museum_package = $request->has('museum_package');
        $extension->pack_city = $request->has('pack_city');
        $extension->active = $request->has('active');
        $extension->itinerary = $request->has('itinerary');
        $extension->assistance = $request->has('assistance');
        $extension->trunks = $request->has('trunks');
        $extension->charges = $request->has('charges');
        $extension->taxes = $request->has('taxes');
        $extension->emergency = $request->has('emergency');
        $extension->local_contact = $request->has('local_contact');
        $extension->folders = $request->has('folders');
        $extension->labels = $request->has('labels');
        $extension->destination = $request->has('destination');
        $extension->tips = $request->has('tips');
        $extension->exhibitor_tips = $request->has('exhibitor_tips');
        $extension->save();

        config(['app.locale' => 'en']);
        $extension = new Extension($request->all());
        $extension->slug = Str::slug($extension->name);
        $extension->type = 'extension';
        $extension->region_id = $request['region'];
        $itinerary_file = $request->file('itinerary_file');
        if($itinerary_file) {
            $nameItinerary_file = "pdf_".time().".".$itinerary_file->guessExtension();
            Storage::disk('public')->put('/files/extensions/' . $nameItinerary_file, \File::get($itinerary_file));
            $extension->itinerary_file = '/storage/files/extensions/'.$nameItinerary_file;
        }
        $extension->destination_id = $request['destination_id'];
        $extension->category_id = $request['category'];
        $extension->museum_package = $request->has('museum_package');
        $extension->pack_city = $request->has('pack_city');
        $extension->active = $request->has('active');
        $extension->itinerary = $request->has('itinerary');
        $extension->assistance = $request->has('assistance');
        $extension->trunks = $request->has('trunks');
        $extension->charges = $request->has('charges');
        $extension->taxes = $request->has('taxes');
        $extension->emergency = $request->has('emergency');
        $extension->local_contact = $request->has('local_contact');
        $extension->folders = $request->has('folders');
        $extension->labels = $request->has('labels');
        $extension->destination = $request->has('destination');
        $extension->tips = $request->has('tips');
        $extension->exhibitor_tips = $request->has('exhibitor_tips');
        $extension->save();

        $extension->leagues()->sync($request['leagues']);

        return redirect('admin/extensions')->with('success', 'La extensión se creo con exito');
    }

    /**
     * Display the specified resource.
     *
     * @param  string  $slug
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $extension = Extension::where('type', 'extension')->where('slug', 'LIKE', '%'.$slug.'%' )->first();
        $image = Image::where('type', 'extensions')->where('reference', $extension->id)->first();
        $images = Image::where('type', 'extensions')->where('reference', $extension->id)->get();
        $description = strip_tags($extension->description);
        $description = html_entity_decode($description);

        return view('public.main.extension', compact('extension', 'image', 'images', 'description'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $extension = Extension::findOrFail($id);
        $destinations = Destination::where('region_id', $extension->region_id)->get();
        $images = Image::where('type', 'extensions')->where('reference', $id)->get();
        return view('administrador.extensions.edit', compact('extension', 'images', 'destinations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        config(['app.locale' => 'es']);
        $extension = Extension::findOrFail($id);
        $extension->fill($request->all());
        $extension->region_id = $request['region'];
        $extension->destination_id = $request['destination_id'];
        $itinerary_file = $request->file('itinerary_file');
        if($itinerary_file) {
            $nameItinerary_file = "pdf_".time().".".$itinerary_file->guessExtension();
            Storage::disk('public')->put('/files/extensions/' . $nameItinerary_file, \File::get($itinerary_file));
            $extension->itinerary_file = '/storage/files/extensions/'.$nameItinerary_file;
        }
        $extension->category_id = $request['category'];
        $extension->slug = Str::slug($extension->name);
        $extension->museum_package = $request->has('museum_package');
        $extension->pack_city = $request->has('pack_city');
        $extension->active = $request->has('active');
        $extension->itinerary = $request->has('itinerary');
        $extension->assistance = $request->has('assistance');
        $extension->trunks = $request->has('trunks');
        $extension->charges = $request->has('charges');
        $extension->taxes = $request->has('taxes');
        $extension->emergency = $request->has('emergency');
        $extension->local_contact = $request->has('local_contact');
        $extension->folders = $request->has('folders');
        $extension->labels = $request->has('labels');
        $extension->destination = $request->has('destination');
        $extension->tips = $request->has('tips');
        $extension->exhibitor_tips = $request->has('exhibitor_tips');
        $extension->save();

        config(['app.locale' => 'en']);
        $extension = Extension::findOrFail($id);
        $extension->fill($request->all());
        $extension->region_id = $request['region'];
        $itinerary_file = $request->file('itinerary_file');
        if($itinerary_file) {
            $nameItinerary_file = "pdf_".time().".".$itinerary_file->guessExtension();
            Storage::disk('public')->put('/files/extensions/' . $nameItinerary_file, \File::get($itinerary_file));
            $extension->itinerary_file = '/storage/files/extensions/'.$nameItinerary_file;
        }
        $extension->destination_id = $request['destination_id'];
        $extension->category_id = $request['category'];
        $extension->slug = Str::slug($extension->name);
        $extension->museum_package = $request->has('museum_package');
        $extension->pack_city = $request->has('pack_city');
        $extension->active = $request->has('active');
        $extension->itinerary = $request->has('itinerary');
        $extension->assistance = $request->has('assistance');
        $extension->trunks = $request->has('trunks');

resources/views/administrador/extensions/list.blade.php
@extends('administrador.layouts.app-admin')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                @if($title == 'Extensiones')
                    <a href="{{route('extensions.create')}}" class="-btn-agregar">
                @elseif($title == 'México')
                    <a href="{{route('mexico.create')}}" class="-btn-agregar">
                @elseif($title == 'Ofertas')
                    <a href="{{route('offers.create')}}" class="-btn-agregar">
                @else
                    <a href="{{route('trips.create')}}" class="-btn-agregar">
                @endif
                    <i class="fas fa-user-plus"></i>
                    Agregar
                </a>
            </div>
        </div>
        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('success') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        {{$title}}
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover mt-3">
                            <thead>
                            <tr>
                                <th>Nombre</th>
                                @if($title != 'Ofertas')
                                    <th>Código</th>
                                @endif
                                <th>Región</th>
                                <th>Categoria</th>
                                <th width="200px">Fecha Inicio/Fin</th>
                                <th colspan="2" width="50px">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($extensions->sortby('name') as $extension)
                                <tr>
                                    <td>
                                        @if($title == 'Extensiones')
                                            <a href="{{route('extensions.edit', ['extension' => $extension->id])}}">
                                        @elseif($title == 'México')
                                            <a href="{{route('mexico.edit', ['mexico' => $extension->id])}}">
                                        @elseif($title == 'Ofertas')
                                            <a href="{{route('offers.edit', ['offer' => $extension->id])}}">
                                        @else
                                            <a href="{{route('trips.edit', ['trip' => $extension->id])}}">
                                        @endif
                                            {{$extension->name == '' ? 'edit':$extension->name}}
                                        </a>
                                    </td>
                                    @if($title != 'Ofertas')
                                        <td>{{$extension->code}}</td>
                                    @endif
                                    <td>{{$extension->region->region}}</td>
                                    <td>{{$extension->category->category}}</td>
                                    <td>
                                        {{$extension->startDate}}<br>
                                        {{$extension->endDate}}
                                    </td>
                                    <td width="10px">
                                        @if($title == 'Extensiones')
                                            <form method="POST" action="{{ route('extensions.active', ['id' => $extension->id]) }}" class="form-check-inline">
                                        @elseif($title == 'México')
                                            <form method="POST" action="{{ route('mexico.active', ['id' => $extension->id]) }}" class="form-check-inline">
                                        @elseif($title == 'Ofertas')
                                            <form method="POST" action="{{ route('offers.active', ['id' => $extension->id]) }}" class="form-check-inline">
                                        @else
                                            <form method="POST" action="{{ route('trips.active', ['id' => $extension->id]) }}" class="form-check-inline">
                                        @endif
                                            @csrf
                                            <button type="submit" class="btn">
                                                @if($extension->active)
                                                    <i class="fa fa-power-off -on"></i>
                                                @else
                                                    <i class="fa fa-power-off -off"></i>
                                                @endif
                                            </button>
                                        </form>
                                    </td>
                                    <td width="10px">
                                        @if($title == 'Extensiones')
                                            <form method="POST" action="{{ route('extensions.destroy', ['extension' => $extension->id]) }}" class="form-check-inline">
                                        @elseif($title == 'México')
                                            <form method="POST" action="{{ route('mexico.destroy', ['mexico' => $extension->id]) }}" class="form-check-inline">
                                        @else
                                            <form method="POST" action="{{ route('trips.destroy', ['trip' => $extension->id]) }}" class="form-check-inline">
                                        @endif
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn text-danger">
                                                <i class="fa fa-trash-alt"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection