routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('storage-link', function (){
    \Illuminate\Support\Facades\Artisan::call('storage:link');
});

Auth::routes();

Route::post('quotation', [\App\Http\Controllers\EmailsController::class, 'quotation'])->name('quotation');


Route::group(['middleware' => ['lang']], function () {
    Route::get('lang/{lang}', function ($lang) {
        session(['lang' => $lang]);
        return \Redirect::back();
    })->where([
        'lang' => 'en|es'
    ]);
    Route::get('/', [\App\Http\Controllers\MainController::class, 'index'])->name('index');
    Route::get('/noticias', [\App\Http\Controllers\MainController::class, 'index'])->name('news');
    Route::get('/testimoniales', [\App\Http\Controllers\MainController::class, 'index'])->name('testimonials');
    Route::get('/aviso-de-privacidad', [\App\Http\Controllers\MainController::class, 'noticePrivacy'])->name('noticeOfPrivacy');
    Route::get('/quienes-somos', [\App\Http\Controllers\MainController::class, 'about'])->name('about');
    Route::get('/servicios/{item}', [\App\Http\Controllers\MainController::class, 'services'])->name('services');
    Route::get('/eventos', [\App\Http\Controllers\MainController::class, 'events'])->name('events');
    Route::get('/eventos/{slug}', [\App\Http\Controllers\FairController::class, 'show'])->name('event');
    Route::post('/events/component', [\App\Http\Controllers\MainController::class, 'eventsChange']);
    Route::get('/extensiones', [\App\Http\Controllers\MainController::class, 'extensions'])->name('extensions');
    Route::get('/extensiones/{slug}', [\App\Http\Controllers\ExtensionController::class, 'show'])->name('extension');
    Route::post('/extensions/component', [\App\Http\Controllers\MainController::class, 'extensionsChange']);
    Route::get('/mexico', [\App\Http\Controllers\MainController::class, 'mexico'])->name('mexico');
    Route::get('/mexico/{slug}', [\App\Http\Controllers\MexicoController::class, 'show'])->name('mex');
    Route::post('/mexico/component', [\App\Http\Controllers\MainController::class, 'mexicoChange']);
    Route::get('/viajes-especiales', [\App\Http\Controllers\MainController::class, 'specialTrips'])->name('specialTrips');
    Route::get('/viajes-especiales/{slug}', [\App\Http\Controllers\SpecialTripsContoller::class, 'show'])->name('specialTrip');
    Route::post('/viajes_especiales/component', [\App\Http\Controllers\MainController::class, 'specialTripsChange']);
    Route::get('/testimoniales', [\App\Http\Controllers\MainController::class, 'testimonials'])->name('testimonials');
    Route::get('/noticias', [\App\Http\Controllers\MainController::class, 'news'])->name('news');
    Route::get('/noticias/{slug}', [\App\Http\Controllers\MainController::class, 'newsShow'])->name('newsShow');
    Route::get('/blog', [\App\Http\Controllers\MainController::class, 'blogs'])->name('blogs');
    Route::get('/blog/{slug}', [\App\Http\Controllers\MainController::class, 'blog'])->name('blog');
    Route::get('/ofertas', [\App\Http\Controllers\MainController::class, 'offers'])->name('offers');
    Route::post('/offers/component', [\App\Http\Controllers\MainController::class, 'offersChange']);
    Route::get('/ofertas/{slug}', [\App\Http\Controllers\OfferController::class, 'show'])->name('offer');
    Route::get('/contacto', [\App\Http\Controllers\MainController::class, 'contact'])->name('contact');
});


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'lang']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('/leagues', \App\Http\Controllers\LeagueController::class)->except(['show']);
    Route::post('/leagues/active/{id}', [\App\Http\Controllers\LeagueController::class, 'active'])->name('leagues.active');
    Route::resource('/fairs', \App\Http\Controllers\FairController::class)->except(['show']);
    Route::post('/fairs/active/{id}', [\App\Http\Controllers\FairController::class, 'active'])->name('fairs.active');
    Route::post('/fairs/star/{id}', [\App\Http\Controllers\FairController::class, 'star'])->name('fairs.star');
    Route::resource('/extensions', \App\Http\Controllers\ExtensionController::class)->except(['show']);
    Route::post('/extensions/active/{id}', [\App\Http\Controllers\ExtensionController::class, 'active'])->name('extensions.active');
    Route::resource('/mexico', \App\Http\Controllers\MexicoController::class)->except(['show']);
    Route::post('/mexico/active/{id}', [\App\Http\Controllers\MexicoController::class, 'active'])->name('mexico.active');
    Route::resource('/trips', \App\Http\Controllers\SpecialTripsContoller::class)->except(['show']);
    Route::post('/trips/active/{id}', [\App\Http\Controllers\SpecialTripsContoller::class, 'active'])->name('trips.active');
    Route::resource('/news', \App\Http\Controllers\NewsController::class)->except(['show']);
    Route::post('/news/active/{id}', [\App\Http\Controllers\NewsController::class, 'active'])->name('news.active');
    Route::resource('/blogs', \App\Http\Controllers\BlogController::class)->except(['show']);
    Route::post('/blogs/active/{id}', [\App\Http\Controllers\BlogController::class, 'active'])->name('blogs.active');
    Route::resource('/offers', \App\Http\Controllers\OfferController::class)->except(['show']);
    Route::post('/offers/active/{id}', [\App\Http\Controllers\OfferController::class, 'active'])->name('offers.active');
    Route::resource('/images', \App\Http\Controllers\ImageController::class)->except(['show', 'index', 'update', 'edit']);
    Route::get('/images/{id}', [\App\Http\Controllers\ImageController::class, 'destroy'])->name('images.destroy');
    Route::resource('/promotions', \App\Http\Controllers\PromotionController::class)->except(['show']);
    Route::post('/promotions/active/{id}', [\App\Http\Controllers\PromotionController::class, 'active'])->name('promotions.active');
    Route::resource('/users', \App\Http\Controllers\UserController::class)->except(['show']);
    Route::post('/users/active/{id}', [\App\Http\Controllers\UserController::class, 'active'])->name('users.active');
    Route::resource('/destination/management', \App\Http\Controllers\DestinationManagementController::class)->except(['show']);
    Route::post('/destination/management/active/{id}', [\App\Http\Controllers\DestinationManagementController::class, 'active'])->name('management.active');
});

resources/views/administrador/managements/create.blade.php
@extends('administrador.layouts.app-admin')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1">
                <div class="row">
                    <div class="col-12 d-flex justify-content-between">
                        <h1>Crear Destination Management</h1>
                        <div class="col-2">
                            <a href="{{route('management.index')}}" class="btn btn-primary">
                                <i class="fa fa-list"></i>
                                Lista
                            </a>
                        </div>
                    </div>
                </div>
                <form class="validate-form mb-5" method="POST" action="{{route('management.store')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-12">
                            <label for="">Liga</label>
                            <input type="text" class="form-control mt-3 @error('url') is-invalid @enderror" placeholder="Url" required name="url" value="{{old('url')}}">
                            @error('url')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-4">
                            <label class="text-center">Imagen</label>
                            <br>
                            <img src="{{asset('images/missing.png')}}" class="img-fluid" alt="Sin imagen" id="poster">
                        </div>
                        <div class="col-8">
                            <br><br>
                            <div class="alert alert-primary" role="alert">
                                <i class="fa fa-file-image"></i>
                                Imagen (Formato png, jpg o jpeg 224 x 170 resolución 72 dpi max 900kb)<br>
                            </div>

                            <div class="upload-btn-wrapper" id="btnposter">
                                <button class="btn btn-primary">Selecciona un archivo</button>
                                <input type="file" name="image" accept="image/*" onchange="loadFilePoster(event)">
                            </div>
                            <div id="deleteposter">
                                <a class="btn btn-danger" onclick="deletePoster()">Eliminar Imagen</a>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-3 offset-9">
                            <button type="submit" class="btn btn-block btn-primary">
                                <i class="fa fa-save"></i>
                                Guardar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
<script type="text/javascript">
    document.getElementById('deleteposter').style.display = 'none';
    function deletePoster(){
        document.getElementById('deleteposter').style.display = 'none';
        var image = document.getElementById('poster');
        image.src = '/images/missing.png';
        image.value = "";
    }
    var loadFilePoster = function(event) {
        var reader = new FileReader();
        reader.onload = function(){
            var image = document.getElementById('poster');
            image.src = reader.result;
        };
        reader.readAsDataURL(event.target.files[0]);
        document.getElementById('btnposter').style.display = 'none';
        document.getElementById('deleteposter').style.display = 'block';
    };
</script>
@endsection

resources/views/administrador/managements/edit.blade.php
@extends('administrador.layouts.app-admin')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1">
                <div class="row">
                    <div class="col-12 d-flex justify-content-between">
                        <h1>Actualizar Destination Management</h1>
                        <div class="col-2">
                            <a href="{{route('management.index')}}" class="btn btn-primary">
                                <i class="fa fa-list"></i>
                                Lista
                            </a>
                        </div>
                    </div>
                </div>
                <form class="validate-form mb-5" method="POST" action="{{route('management.update', [$management->id])}}" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                    <div class="row">
                        <div class="col-12">
                            <label for="">Liga</label>
                            <input type="text" class="form-control mt-3 @error('url') is-invalid @enderror" placeholder="Url" required name="url" value="{{old('url', $management->url)}}">
                            @error('url')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col-4">
                            <label class="text-center">Imagen</label>
                            <br>
                            @if($management->image)
                                <img src="{{asset($management->image)}}" class="img-fluid" alt="{{$management->image}}" id="poster">
                            @else
                                <img src="{{asset('images/missing.png')}}" class="img-fluid" alt="Sin imagen" id="poster">
                            @endif
                        </div>
                        <div class="col-8">
                            <br><br>
                            <div class="alert alert-primary" role="alert">
                                <i class="fa fa-file-image"></i>
                                Imagen (Formato png, jpg o jpeg 224 x 170 resolución 72 dpi max 900kb)<br>
                            </div>

                            <div class="upload-btn-wrapper" id="btnposter">
                                <button class="btn btn-primary">Selecciona un archivo</button>
                                <input type="file" name="image" accept="image/*" onchange="loadFilePoster(event)">
                            </div>
                            <div id="deleteposter">
                                <a class="btn btn-danger" onclick="deletePoster()">Eliminar Imagen</a>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-3 offset-9">
                            <button type="submit" class="btn btn-block btn-primary">
                                <i class="fa fa-save"></i>
                                Guardar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        document.getElementById('deleteposter').style.display = 'none';
        function deletePoster(){
            document.getElementById('deleteposter').style.display = 'none';
            var image = document.getElementById('poster');
            image.src = '/images/missing.png';
            image.value = "";
        }
        var loadFilePoster = function(event) {
            var reader = new FileReader();
            reader.onload = function(){
                var image = document.getElementById('poster');
                image.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
            document.getElementById('btnposter').style.display = 'none';
            document.getElementById('deleteposter').style.display = 'block';
        };
    </script>
@endsection

resources/views/administrador/managements/list.blade.php
@extends('administrador.layouts.app-admin')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <a href="{{route('management.create')}}" class="-btn-agregar">
                    <i class="fas fa-user-plus"></i>
                    Agregar
                </a>
            </div>
        </div>
        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('success') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        Destination Management
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover mt-3">
                            <thead>
                            <tr>
                                <th width="200px">Imagen</th>
                                <th>Liga</th>
                                <th colspan="3" width="50px">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($managements->sortby('name') as $management)
                                <tr>
                                    <td width="200px">
                                        <a href="{{route('management.edit', ['management' => $management->id])}}">
                                            @if($management->image)
                                                <img src="{{asset($management->image)}}" class="img-fluid" alt="{{$management->image}}" id="logo">
                                            @else
                                                <img src="{{asset('images/missing.png')}}" class="img-fluid" alt="Sin imagen" id="logo">
                                            @endif
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{route('management.edit', ['management' => $management->id])}}">
                                            {{$management->url}}
                                        </a>
                                    </td>
                                    <td width="10px">
                                        <form method="POST" action="{{ route('management.active', ['id' => $management->id]) }}">
                                            @csrf
                                            <button type="submit" class="btn">
                                                @if($management->active)
                                                    <i class="fa fa-power-off -on"></i>
                                                @else
                                                    <i class="fa fa-power-off -off"></i>
                                                @endif
                                            </button>
                                        </form>
                                    </td>
                                    <td width="10px">
                                        <form method="POST" action="{{ route('management.destroy', ['management' => $management->id]) }}">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn text-danger">
                                                <i class="fa fa-trash-alt"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection